language: php

php:
  - "5.3.3"
  - "5.3"
  - "5.4"

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit -c ./tests/phpunit.xml.dist
  - ./vendor/bin/phpcs --standard=PSR2 library
  - ./vendor/bin/phpcs --standard=PSR2 tests/VoTest
